import { FaPaintBrush, FaCircle, FaSquare, FaPen, FaSprayCan, FaStamp } from 'react-icons/fa';
import { Theme } from './types';

export const colorPresets = [
  { color: '#1a1a1a', name: 'Black' },
  { color: '#4d4d4d', name: 'Dark Gray' },
  { color: '#999999', name: 'Gray' },
  { color: '#ffffff', name: 'White' },
  { color: '#f44e3b', name: 'Red' },
  { color: '#fe9200', name: 'Orange' },
  { color: '#fcdc00', name: 'Yellow' },
  { color: '#dbdf00', name: 'Lime' },
  { color: '#a4dd00', name: 'Light Green' },
  { color: '#68ccca', name: 'Turquoise' },
  { color: '#73d8ff', name: 'Sky Blue' },
  { color: '#aea1ff', name: 'Purple' },
  { color: '#fda1ff', name: 'Pink' },
  { color: '#d33115', name: 'Dark Red' },
  { color: '#e27300', name: 'Dark Orange' },
  { color: '#fcc400', name: 'Dark Yellow' }
];

export const brushPresets = [
  { type: 'normal', name: 'Normal', icon: FaPaintBrush },
  { type: 'round', name: 'Round', icon: FaCircle },
  { type: 'square', name: 'Square', icon: FaSquare },
  { type: 'calligraphy', name: 'Calligraphy', icon: FaPen },
  { type: 'spray', name: 'Spray', icon: FaSprayCan },
  { type: 'pattern', name: 'Pattern', icon: FaStamp }
] as const;

export const sketchpadThemes: Theme[] = [
  {
    name: 'Classic Grid',
    bgColor: '#f0f0f0',
    gridColor: '#e0e0e0',
    gridSize: 20,
    gridOpacity: 0.5,
  },
  {
    name: 'Dark Studio',
    bgColor: '#1a1a1a',
    gridColor: '#333333',
    gridSize: 20,
    gridOpacity: 0.3,
    secondaryGrid: true,
    secondaryGridOpacity: 0.1,
  },
  {
    name: 'Blueprint Pro',
    bgColor: '#1e3a8a',
    gridColor: '#60a5fa',
    gridSize: 30,
    gridOpacity: 0.4,
    secondaryGrid: true,
    secondaryGridOpacity: 0.2,
    secondaryGridColor: '#93c5fd',
  },
  {
    name: 'Minimal Dots',
    bgColor: '#ffffff',
    gridColor: '#94a3b8',
    gridSize: 20,
    isDotted: true,
    dotSize: 2,
    gridOpacity: 0.4,
  },
  {
    name: 'Architect',
    bgColor: '#fffbeb',
    gridColor: '#92400e',
    gridSize: 40,
    gridOpacity: 0.1,
    secondaryGrid: true,
    secondaryGridColor: '#92400e',
    secondaryGridOpacity: 0.05,
    tertiaryGrid: true,
    tertiaryGridSize: 200,
    tertiaryGridOpacity: 0.2,
  },
  {
    name: 'Neon Grid',
    bgColor: '#0f172a',
    gridColor: '#22d3ee',
    gridSize: 30,
    gridOpacity: 0.3,
    glowEffect: true,
    secondaryGrid: true,
    secondaryGridColor: '#e879f9',
    secondaryGridOpacity: 0.2,
  },
  {
    name: 'Isometric',
    bgColor: '#ffffff',
    gridColor: '#cbd5e1',
    isIsometric: true,
    gridSize: 30,
    gridOpacity: 0.3,
    secondaryGridOpacity: 0.15,
  },
  {
    name: 'Graph Paper Pro',
    bgColor: '#f8fafc',
    gridColor: '#64748b',
    gridSize: 20,
    gridOpacity: 0.2,
    secondaryGrid: true,
    secondaryGridColor: '#64748b',
    secondaryGridOpacity: 0.1,
    rulerLines: true,
    rulerColor: '#475569',
  },
  {
    name: 'Midnight Studio',
    bgColor: '#020617',
    gridColor: '#1e293b',
    gridSize: 25,
    gridOpacity: 0.4,
    starField: true,
    secondaryGrid: true,
    secondaryGridColor: '#0ea5e9',
    secondaryGridOpacity: 0.1,
  },
  {
    name: 'Creative Canvas',
    bgColor: '#fdf4ff',
    gridColor: '#d946ef',
    gridSize: 35,
    gridOpacity: 0.2,
    patternType: 'honeycomb',
    secondaryGridColor: '#a855f7',
    secondaryGridOpacity: 0.1,
  },
  {
    name: 'Matrix',
    bgColor: '#000000',
    gridColor: '#00ff00',
    gridSize: 20,
    gridOpacity: 0.2,
    glowEffect: true,
    secondaryGrid: true,
    secondaryGridColor: '#003300',
    secondaryGridOpacity: 0.1,
  },
  {
    name: 'Retro Paper',
    bgColor: '#fff5e6',
    gridColor: '#ffcc80',
    gridSize: 25,
    gridOpacity: 0.3,
    isDotted: true,
    dotSize: 1,
    rulerLines: true,
    rulerColor: '#ffab40',
  },
  {
    name: '3D Grid',
    bgColor: '#f8f9fa',
    gridColor: '#4a5568',
    gridSize: 40,
    gridOpacity: 0.2,
    isIsometric: true,
    secondaryGrid: true,
    secondaryGridColor: '#718096',
    secondaryGridOpacity: 0.1,
  },
  {
    name: 'Night Sky',
    bgColor: '#1a1a2e',
    gridColor: '#4a5568',
    gridSize: 30,
    gridOpacity: 0.2,
    starField: true,
    glowEffect: true,
    secondaryGrid: true,
    secondaryGridColor: '#0ea5e9',
    secondaryGridOpacity: 0.1,
  },
  {
    name: 'Gradient Grid',
    bgColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    gridColor: '#ffffff',
    gridSize: 25,
    gridOpacity: 0.15,
    glowEffect: true,
    secondaryGrid: true,
    secondaryGridColor: '#ffffff',
    secondaryGridOpacity: 0.1,
  },
  {
    name: 'Pink Paradise',
    bgColor: '#ffd6e6',
    gridColor: '#ff69b4',
    gridSize: 25,
    gridOpacity: 0.6,
    secondaryGrid: true,
    secondaryGridColor: '#ff1493',
    secondaryGridOpacity: 0.3,
    glowEffect: true,
  },
  {
    name: 'Forest Grid',
    bgColor: '#e6ffe6',
    gridColor: '#228B22',
    gridSize: 25,
    gridOpacity: 0.6,
    secondaryGrid: true,
    secondaryGridColor: '#006400',
    secondaryGridOpacity: 0.3,
    glowEffect: true,
  },
]; 